# Generated by Django 3.1.3 on 2023-03-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0005_admin_helath_csv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_Helath_CSV',
            new_name='Admin_Health_CSV',
        ),
    ]
